spring:
    application:
        name: service-registry

server:
    port: 8761

# This property indicates whether this instance should register with Eureka server as a service. 
# In this case, the value is set to false, which means that this instance will not register with the Eureka server.
eureka:
    client:
        register-with-eureka: false

# This property indicates whether this instance should fetch the registry information from the Eureka server.
eureka:
    client:
        fetch-registry: false

